CREATE DATABASE IF NOT EXISTS FinalProject;
USE FinalProject;

CREATE TABLE IF NOT EXISTS Bill
(
rate VARCHAR (50) NOT NULL,
Payments VARCHAR (50),
Date VARCHAR (50),
Total VARCHAR (50),
Payment_date VARCHAR (50),
BillNo INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Contract
(
Activation_date VARCHAR (50) NOT NULL,
address VARCHAR (100) NOT NULL,
Meter_Number INT NOT NULL,
prev_reading INT,
rate VARCHAR (50) NOT NULL,
ContNo INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Customer
(
address VARCHAR (100) NOT NULL,
Consumption INT,
Name VARCHAR (50) NOT NULL, 
CustID INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Address
(
Meter_Number INT NOT NULL,
CustID INT NOT NULL,
address VARCHAR (100) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Meter
(
address VARCHAR (100) NOT NULL,
Consumption INT,
ContNo INT NOT NULL,
Meter_Number INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Employee
(
address VARCHAR (100) NOT NULL,
Meter_Number INT NOT NULL,
EmplNo INT NOT NULL PRIMARY KEY
);

SHOW TABLES;